name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100-preview.6.23330.14
    - name: Install .NET MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Tzy.MAUI.DotNet8/Tzy.MAUI.DotNet8.csproj -c Release -f net8.0.0-preview.6-android /p:AndroidSigningKeyStore=myapp.keystore /p:AndroidSigningKeyAlias=key /p:AndroidSigningKeyPass="Holzoo@123" /p:AndroidSigningStorePass="Holzoo@123" --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
    - name: Upload artifact to App Center
      uses: actions/upload-artifact@v3.1.0
      with:
        name: appcenter-artifact
        path: com.companyname.tzy.maui.build-Signed.apk
    - name: Deploy to App Center
      uses: actions/appcenter-action@v3
      with:
        app_secret: ${{secrets.APP_CENTER_TOKEN}}
        app_path: ./com.companyname.tzy.maui.build-Signed.apk
        distribution_group: Testers
        notify_testers: true
