name: Build and Sign APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows machines

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100-preview.6.23330.14

    - name: Restore and build
      run: dotnet build -c Release

    - name: Sign the APK
      run: |
        # Replace these values with your own
        $KEYSTORE_FILE = 'myapp.keystore'
        $KEY_ALIAS = 'key'
        $KEYSTORE_PASSWORD = 'Holzoo@123'
        $KEY_PASSWORD = 'Holzoo@123'
        $APK_FILE = ' ./**/*.apk'

        # Sign the APK
        jarsigner -keystore $KEYSTORE_FILE -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD -sigalg SHA1withRSA -digestalg SHA1 -signedjar $APK_FILE $APK_FILE $KEY_ALIAS

    - name: Zipalign the APK
      run: |
        # You may need to specify the full path to zipalign
        'C:\Program Files (x86)\Android\android-sdk\build-tools\version\zipalign' -f -v 4 $APK_FILE $APK_FILE-aligned.apk
        mv $APK_FILE-aligned.apk $APK_FILE

    - name: Upload the signed APK
      uses: actions/upload-artifact@v2
      with:
        name: signed-apk
        path: $APK_FILE
